### ISSUE TITLE
Support for issuetype in Jira Plugin for Kestra

### ISSUE THREAD

**Issue by marsalan06** [kestra-io/plugin-jira#12]
### Expected Behavior

I'm experiencing an issue when trying to create Jira issues using the io.kestra.plugin.jira.issues.Create plugin in Kestra. The Jira API requires the issuetype field to be present in the request body, but the plugin currently does not support this field, leading to a 400 Bad Request error when attempting to create an issue.

While the curl request requires issue type field in it.

`id: create_issue
type: io.kestra.plugin.jira.issues.Create
baseUrl: https://your-domain.atlassian.net
username: your_email@example.com
password: "{{ secret('your_jira_api_token') }}"
projectKey: MYPROJECT
summary: "Workflow failed"
description: "The workflow execution has failed. See the link below for more details."
labels:
  - bug
  - workflow```

### Actual Behaviour

The plugin does not accept the issuetype field, resulting in a 400 Bad Request error when communicating with the Jira API. This error indicates that the issuetype field is missing from the request, which is mandatory for creating issues in Jira.

While using Curl request if we do not send it we get 
{"errorMessages":[],"errors":{"issuetype":"Specify an issue type"}}

### Steps To Reproduce

Create a new Kestra workflow with the io.kestra.plugin.jira.issues.Create plugin.

Configure the plugin with the following parameters:

yaml

```
id: create_issue
type: io.kestra.plugin.jira.issues.Create
baseUrl: https://your-domain.atlassian.net
username: your_email@example.com
password: "{{ secret('your_jira_api_token') }}"
projectKey: MYPROJECT
summary: "Workflow failed"
description: "The workflow execution has failed. See the link below for more details."
labels:
  - bug
  - workflow
```

### Environment Information

- Kestra Version: 0.18.8
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by MustafaMunir123** [comment]
Hey @Ben8t 
Can I pick this up?
Thanks!
